name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please provide clear reproduction steps and expected behavior.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the problem?
      placeholder: Brief bug summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, commands, and inputs
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
      description: App version, tag, or commit hash
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, runtime, browser, dependency versions
